### PR TITLE
150 fix crk spellcheck

### LINKED ISSUE #150: Fix crk spellcheck lambda and Spellchecker service
The infrastructure for the spellchecker is now deployed, but the lambda and service are broken

### PR DESCRIPTION
**Pull request by danielfay**
Transcribe now uses the bulk-lookup of the new nodejs spellchecker lambda. The initial migration of the lambda from python to nodejs was completely broken and has been rewritten.

I'm not sure how well the new function and FSTs are working, but some words are definitely being spellchecked.

## Misc changes
- The peaks lambda's memory is now 3GB (the most our AWS account allows right now)
- The args passed to the commands in the peaks lambda have been escaped to support file names with spaces
- Transcribe no longer 404s when trying to get files with spaces

### CODE REVIEW

**Comment by danielfay** [comment]
@aaronfay If this looks good to you then you are welcome to merge it after you approve. I may be sleeping when you take a look at this and I know you need it 😃

File: src/services/spellCheckerService.ts [hunk 1]
```diff
@@ -56,21 +57,18 @@ class SpellCheckerServiceImpl {
...
-        },
-        body: JSON.stringify(words),
+      // Use Amplify's REST API client with the spellcheck API
+      const { response } = await post({
+        apiName: 'spellcheck',
+        path: `/${languageCode}/bulk-lookup`,
+        options: {
+          body: words
+        }
       });
```
Comment (aaronfay) [inline src/services/spellCheckerService.ts:69]: Slick. I've never used Amplify's APIs "properly", this is so clean.

File: src/services/spellCheckerService.ts [hunk 2]
```diff
@@ -56,21 +57,18 @@ class SpellCheckerServiceImpl {
...
-
-      if (!response.ok) {
-        throw new Error(`API request failed: ${response.status}`);
-      }
-
-      const result = await response.json();
+      const res = await response;
```
Comment (aaronfay) [inline src/services/spellCheckerService.ts:70]: You don't need to change this, but I get sticky about "half word variables" like `err` and `fmt`. _I_ would just call this `raw` or `rawResponse` just for the sake of readability. In this case this is pretty minor so don't feel like you need to change it, just be prepared to be nitpicked on this in the future ;)

**Review by aaronfay — APPROVED** [review]
Nice work 👍🏻

File: src/services/spellCheckerService.ts (hunk 1 above)
Comment (danielfay) [reply src/services/spellCheckerService.ts:69]: Claude originally was trying to do the AWS auth itself (since the api is private and needs a logged in user) and was really struggling.

I pointed it to the docs showing that it was build into amplify and suddenly 20 lines to make the call turned into those 6. I was really impressed as well aha.

File: src/services/spellCheckerService.ts (hunk 2 above)
Comment (danielfay) [reply src/services/spellCheckerService.ts:70]: That's annoying, I apparently only glanced over the recommended changes, because I wouldn't have left that like that either.

Feel free to call it out if it happens again, I'll keep a better eye on it as well.
